# Nome do site
site_name: "Passe Livre Estudantil"

# Descrição
site_description: "Repositório de documentos de Interação Humano-Computador"
repo_name: '2024.2-Grupo07'
repo_url: 'https://github.com/Interacao-Humano-Computador/2024.2-Grupo07'

# Tema do MkDocs
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: claro
      toggle:
        icon: material/circle-half-full
        name: Mudar para o modo escuro

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/circle-half-full
        name: Mudar para o modo claro

  language: pt-BR
  favicon: 
  logo: ##logo do site escolhido

# Configura a navegação do site
nav:
  - Introdução: index.md
  - Atas: 
    - Ata 1: atas/ata-1.md
  - Planejamento:
    - Cronograma: planejamento/cronograma.md
    - Metodologia: planejamento/metodologia.md
    - Design: planejamento/design.md
    - Ferramentas: planejamento/ferramentas.md
    - Heatmap: planejamento/heatmap.md
    - Sites avaliados: planejamento/sites_avaliados.md
    - Site escolhido: planejamento/sites_escolhidos.md
  - Verificação:
    - Entrega 01:
      - Inspeção grupo 07: verificacoes/entrega01/verificacaoGrupo07.md
      - Inspeção grupo 08: verificacoes/entrega01/verificacaoGrupo08.md
      - Planejamento da Verificação da Etapa 1: verificacoes/entrega01/planejamento.md
      - Cronograma: verificacoes/entrega01/cronogramav.md
      - Ferramentas: verificacoes/entrega01/ferramentasv.md
      - Processo de design: verificacoes/entrega01/designv.md
      - Sites avaliados: verificacoes/entrega01/siteav.md
      - Site escolhido: verificacoes/entrega01/siteev.md
      - Metodologia:  verificacoes/entrega01/metodologiav.md
  - Análise de Requisitos:
    - Aspectos Éticos: analisedeRequsitos/aspectosEticos.md
    - Perfíl de Usuario: analisedeRequsitos/perfildeUsuario.md
    - Cenários: analisedeRequsitos/cenarios.md
    - Personas: analisedeRequsitos/personas.md
    - Analise de Tarefas: analisedeRequsitos/analisedeTarefas.md
    - Termo de Consentimento: analisedeRequsitos/termodeConsentimento.md
    
    





extra:
  version:
    provider: 
