# Nome do site
site_name: "Passe Livre Estudantil"

# Descrição
site_description: "Repositório de documentos de Interação Humano-Computador"
repo_name: "2024.2-Grupo07"
repo_url: "https://github.com/Interacao-Humano-Computador/2024.2-Grupo07"

# Tema do MkDocs
theme:
  name: material
  features:
    - navigation.instant # Carrega páginas instantaneamente
    - navigation.tracking # Permite rastrear a navegação
    - navigation.tabs # Habilita abas de navegação no topo
    - navigation.tabs.sticky # Abas fixas na parte superior
    - navigation.top # Move o menu para o topo
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/circle-half-full
        name: Mudar para o modo claro

    - media: "(prefers-color-scheme: light)"
      scheme: claro
      toggle:
        icon: material/circle-half-full
        name: Mudar para o modo escuro

  language: pt-BR
  favicon: assets/passeLivreEstudantilFavicon.png
  logo: assets/passeLivreEstudantil.png
  navigation:
    tabs: true

# Configura a navegação do site
nav:
  - Introdução: index.md
  - Atas:
      - Ata 1: atas/ata-1.md
      - Ata 2: atas/ata-2.md
      - Ata 3: atas/ata_3.md
  - Planejamento:
      - Cronograma: planejamento/cronograma.md
      - Metodologia: planejamento/metodologia.md
      - Design: planejamento/design.md
      - Ferramentas: planejamento/ferramentas.md
      - Heatmap: planejamento/heatmap.md
      - Sites avaliados: planejamento/sites_avaliados.md
      - Site escolhido: planejamento/sites_escolhidos.md
  - Listas de Verificação:
      - Grupo 7:
          - Entrega 01: verificacoes/grupo07/entrega01/verificacao_entrega01_grupo07.md
          - Entrega 02: verificacoes/grupo07/entrega02/verificacao_entrega02_grupo07.md
          - Entrega 03: verificacoes/grupo07/entrega03/verificacao_entrega03_grupo07.md
          - Entrega 04: verificacoes/grupo07/entrega04/verificacao_entrega04_grupo07.md
      - Grupo 8:
          - Entrega 01: verificacoes/grupo08/entrega01/verificacao_entrega01_grupo08.md
          - Entrega 02: verificacoes/grupo08/entrega02/verificacao_entrega02_grupo08.md
          - Entrega 03: verificacoes/grupo08/entrega03/verificacao_entrega_03_grupo08.md
          - Entrega 04: verificacoes/grupo08/entrega04/verificacao_entrega04_grupo08.md
  - Análise de Requisitos:
      - Aspectos Eticos: analise_de_requsitos/aspectos_eticos.md
      - Perfil de Usuario: analise_de_requsitos/perfil_de_usuario.md
      - Personas: analise_de_requsitos/personas.md
      - Cenarios: analise_de_requsitos/cenarios.md
      - Analise de Tarefas:
          - GOMS: analise_de_requsitos/analise_tarefas/goms.md
          - HTA: analise_de_requsitos/analise_tarefas/hta.md
      - Termo de Consentimento: analise_de_requsitos/termo_de_consentimento.md
      - Principios Gerais: analise_de_requsitos/principios_gerais.md
      - Metas de Usabilidade: analise_de_requsitos/metas_de_usabilidade.md
      - Guia de estilo: analise_de_requsitos/guia_de_estilo.md
      - Caracteristicas Gerais: analise_de_requsitos/caracteristicas.md
  - Design, Avaliacao e Desenvolvimento:
      - Nivel 1:
          - Analise de Tarefas:
              - Planejamento da Avaliacao da Analise de Tarefas: design_avaliacao_desenvolvimento/nivel01/analise_de_tarefas/planejamento_avaliacao.md
              - Planejamento do Relato dos Resultados da Avaliacao: design_avaliacao_desenvolvimento/nivel01/analise_de_tarefas/planejamento_relato_resultados_avaliacao.md
              - Relato do Resultado: design_avaliacao_desenvolvimento/nivel01/analise_de_tarefas/relato_resultado.md
          - Storyboard:
              - Planejamento da Avaliacao do Storyboard: design_avaliacao_desenvolvimento/nivel01/storyboard/planejamento_avaliacao.md
              - Planejamento do Relato dos Resultados: design_avaliacao_desenvolvimento/nivel01/storyboard/planejamento_relato_resultados_avaliacao.md
              - Relato do Resultado: design_avaliacao_desenvolvimento/nivel01/storyboard/relato_resultado.md
              - Storyboards: design_avaliacao_desenvolvimento/nivel01/storyboard/storyboards.md
  - Apresentações:
      - Entrega 1: apresentacoes/entrega1/entrega1.md
      - Entrega 2: apresentacoes/entrega2/entrega2.md
      - Entrega 3: apresentacoes/entrega3/entrega3.md
      - Entrega 4: apresentacoes/entrega4/entrega4.md
extra:
  version:
    provider:
