# Nome do site
site_name: "Passe Livre Estudantil"

# Descrição
site_description: "Repositório de documentos de Interação Humano-Computador"
repo_name: "2024.2-Grupo07"
repo_url: "https://github.com/Interacao-Humano-Computador/2024.2-Grupo07"

# Tema do MkDocs
theme:
  name: material
  features:
    - navigation.instant # Carrega páginas instantaneamente
    - navigation.tracking # Permite rastrear a navegação
    - navigation.tabs # Habilita abas de navegação no topo
    - navigation.tabs.sticky # Abas fixas na parte superior
    - navigation.top # Move o menu para o topo
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/circle-half-full
        name: Mudar para o modo claro

    - media: "(prefers-color-scheme: light)"
      scheme: claro
      toggle:
        icon: material/circle-half-full
        name: Mudar para o modo escuro

  language: pt-BR
  favicon: assets/passeLivreEstudantilFavicon.png
  logo: assets/passeLivreEstudantil.png
  navigation:
    tabs: true

# Configura a navegação do site
nav:
  - Introducao: index.md
  - Atas:
      - Ata 1: atas/ata-1.md
      - Ata 2: atas/ata-2.md
      - Ata 3: atas/ata_3.md
  - Planejamento:
      - Cronograma: planejamento/cronograma.md
      - Metodologia: planejamento/metodologia.md
      - Design: planejamento/design.md
      - Ferramentas: planejamento/ferramentas.md
      - Heatmap: planejamento/heatmap.md
      - Sites avaliados: planejamento/sites_avaliados.md
      - Site escolhido: planejamento/sites_escolhidos.md
      - Indice: planejamento/index.md
  - Verificacao:
      - Verificacao do Grupo 7:
          - Entrega 01:
              - Inspecao: verificacoes/grupo07/entrega01/verificacaoGrupo07.md
              - Planejamento da Verificacao: verificacoes/grupo07/entrega01/planejamento.md
              - Cronograma: verificacoes/grupo07/entrega01/cronogramav.md
              - Ferramentas: verificacoes/grupo07/entrega01/ferramentasv.md
              - Processo de design: verificacoes/grupo07/entrega01/designv.md
              - Sites avaliados: verificacoes/grupo07/entrega01/siteav.md
              - Site escolhido: verificacoes/grupo07/entrega01/siteev.md
              - Metodologia: verificacoes/grupo07/entrega01/metodologiav.md
          - Entrega 02:
              - Planejamento de Verificacao: verificacoes/grupo07/entrega02/planejamentodeVerificacao.md
              - Personas: verificacoes/grupo07/entrega02/personas.md
              - Aspectos Eticos: verificacoes/grupo07/entrega02/aspectosEticos.md
              - Cenarios: verificacoes/grupo07/entrega02/cenarios.md
              - Perfil do Usuario: verificacoes/grupo07/entrega02/perfil_de_usuarios.md
              - Analise de tarefas: verificacoes/grupo07/entrega02/analisedeTarefas.md
              - Guia de Estilo: verificacoes/grupo07/entrega02/guiadeEstilo.md
          - Entrega 03:
              - Planejamento de verificacao: verificacoes/grupo07/entrega03/planejamentoVerificacaoEntrega3.md
              - Principios Gerais: verificacoes/grupo07/entrega03/principiosGerais.md
              - Metas de usabilidade: verificacoes/grupo07/entrega03/metasdeUsabilidade.md
              - Guia de Estilo: verificacoes/grupo07/entrega03/guiadeEstilo.md
              - Caracteristicas Gerais: verificacoes/grupo07/entrega03/caracteristicasGerais.md
          - Entrega 04:
              - Planejamento da Avaliacao da Analise de Tarefas: verificacoes/grupo07/entrega04/planejamentoAvaliacaoAnaliseTarefas.md
              - Planejamento do Relato dos Resultados da Avaliacao: verificacoes/grupo07/entrega04/planejamentoRelatoResultadosAvaliacaoAnaliseTarefas.md
              - Planejamento da Avaliacao do Storyboard: verificacoes/grupo07/entrega04/planejamentoAvaliacaoStoryboard.md
              - Planejamento do Relato dos Resultados: verificacoes/grupo07/entrega04/planejamentoRelatoResultadosAvaliacaoStoryboard.md
              - Planejamento de Verificacao: verificacoes/grupo07/entrega04/planejamentoVericacaoEntrega04.md
              - Storyboards: verificacoes/grupo07/entrega04/storyboards.md
      - Verificacao do Grupo 8:
          - Entrega 01:
              - Inspecao: verificacoes/grupo08/entrega01/verificacao_grupo_08.md
              - Cronograma: verificacoes/grupo08/entrega01/cronograma.md
              - Ferramentas: verificacoes/grupo08/entrega01/ferramentas.md
              - Processo de Design: verificacoes/grupo08/entrega01/processo_de_design.md
              - Site Escolhido: verificacoes/grupo08/entrega01/site_escolhido.md
          - Entrega 02:
              - Planejamento de Verificacao: verificacoes/grupo08/entrega02/planejamento_de_verificacao.md
              - Personas: verificacoes/grupo08/entrega02/personas.md
              - Aspectos Eticos: verificacoes/grupo08/entrega02/aspectos_eticos.md
              - Cenarios: verificacoes/grupo08/entrega02/cenarios.md
              - Perfil do Usuario: verificacoes/grupo08/entrega02/perfil_de_usuario.md
              - Analise de tarefas: verificacoes/grupo08/entrega02/analise_de_tarefas.md
          - Entrega 03: verificacoes/grupo08/entrega03/verificacao_entrega_03.md
          - Entrega 04:
              - Planejamento de Verificacao: verificacoes/grupo08/entrega04/planejamento_verificacao_entrega_04.md
              - Analise de Tarefas:
                  - Planejamento da Avaliacao da Analise de Tarefas: verificacoes/grupo08/entrega04/planejamento_avaliacao_analise_tarefas.md
                  - Planejamento do Relato dos Resultados da Avaliacao: verificacoes/grupo08/entrega04/planejamento_relato_resultados_avaliacao_analise_tarefas.md
              - Storyboard:
                  - Planejamento da Avaliacao do Storyboard: verificacoes/grupo08/entrega04/planejamento_avaliacao_storyboard.md
                  - Planejamento do Relato dos Resultados: verificacoes/grupo08/entrega04/planejamento_relato_resultados_avaliacao_storyboard.md
              - Storyboards: verificacoes/grupo08/entrega04/storyboards.md
  - Analise de Requisitos:
      - Aspectos Eticos: analise_de_requsitos/aspectos_eticos.md
      - Perfil de Usuario: analise_de_requsitos/perfil_de_usuario.md
      - Personas: analise_de_requsitos/personas.md
      - Cenarios: analise_de_requsitos/cenarios.md
      - Analise de Tarefas:
          - GOMS: analise_de_requsitos/analise_tarefas/goms.md
      - Termo de Consentimento: analise_de_requsitos/termo_de_consentimento.md
      - Principios Gerais: analise_de_requsitos/principios_gerais.md
      - Metas de Usabilidade: analise_de_requsitos/metas_de_usabilidade.md
      - Guia de estilo: analise_de_requsitos/guia_de_estilo.md
      - Caracteristicas Gerais: analise_de_requsitos/caracteristicas.md
  - Design, Avaliacao e Desenvolvimento:
      - Nivel 1:
          - Analise de Tarefas:
              - Planejamento da Avaliacao da Analise de Tarefas: design_avaliacao_desenvolvimento/nivel01/analise_de_tarefas/planejamento_avaliacao.md
              - Planejamento do Relato dos Resultados da Avaliacao: design_avaliacao_desenvolvimento/nivel01/analise_de_tarefas/planejamento_relato_resultados_avaliacao.md
              - Relato do Resultado: design_avaliacao_desenvolvimento/nivel01/analise_de_tarefas/relato_resultado.md
          - Storyboard:
              - Planejamento da Avaliacao do Storyboard: design_avaliacao_desenvolvimento/nivel01/storyboard/planejamento_avaliacao.md
              - Planejamento do Relato dos Resultados: design_avaliacao_desenvolvimento/nivel01/storyboard/planejamento_relato_resultados_avaliacao.md
              - Relato do Resultado: design_avaliacao_desenvolvimento/nivel01/storyboard/relato_resultado.md
              - Storyboards: design_avaliacao_desenvolvimento/nivel01/storyboard/storyboards.md
  - Apresentacoes:
      - Entrega 1: apresentacoes/entrega1/entrega1.md
      - Entrega 2: apresentacoes/entrega2/entrega2.md
      - Entrega 3: apresentacoes/entrega3/entrega3.md
      - Entrega 4: apresentacoes/entrega4/entrega4.md
extra:
  version:
    provider:
